spring:
  jpa:
    properties:
      hibernate:
        validator:
          apply_to_ddl: 'false'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  datasource:
    username: { username }
    url: { database_url }
    password: { password }